// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cloud.Data;

#nullable disable

namespace cloud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117120822_Migration-17.11")]
    partial class Migration1711
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cloud.Models.File", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("binned_at")
                        .HasColumnType("datetime");

                    b.Property<long>("bytes")
                        .HasColumnType("bigint");

                    b.Property<string>("extention")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("path")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("сreated_at")
                        .HasColumnType("datetime");

                    b.HasKey("id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("cloud.Models.PhoneVerification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("check_id")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("сreated_at")
                        .HasColumnType("datetime");

                    b.HasKey("id");

                    b.ToTable("phone_verifications", (string)null);
                });

            modelBuilder.Entity("cloud.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("lname")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("sname")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("сreated_at")
                        .HasColumnType("datetime");

                    b.HasKey("id");

                    b.HasIndex("phone")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
